### ISSUE TITLE
Incident summary page

### ISSUE THREAD

**Issue by jclement** [jclement/mattermost-dynamics-bot#1]
Add a basic summary page that includes
- Top level detail
- Notes
- Link to actual Incident in CRM

**Comment by ctrowat** [comment]
I took a little left turn with this one and created an API that can be connected directly to a mattermost outgoing webhook.  It returns a markdown formatted message with the title, company, owner and description of the incident.  I don't have the link working yet or the notes.

**Comment by jclement** [comment]
I've thrown together a really crap incident viewer in Angular and added a link to that from your Mattermost summary.  It also has a link to the CRM.

**Comment by jclement** [comment]
Done
